"""add_pantry_state

Revision ID: f8a4606a8f3b
Revises: 20b2b51ca9d3
Create Date: 2026-09-29 20:14:21.321625
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'f8a4606a8f3b'
down_revision: Union[str, None] = '20b2b51ca9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_items', sa.Column('pantry_status', sa.String(length=30), nullable=False))
    op.add_column('delivery_items', sa.Column('recommended_use_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_items', 'recommended_use_at')
    op.drop_column('delivery_items', 'pantry_status')
    # ### end Alembic commands ###

